ENGINE_PATH: stockfish

# Limits (set to 0 if infinite)
# If no limits are set, each iteration will be run at 2 million nodes by default.
# Setting more than one of these limits may result in undefined behaviour.
DEPTH: 0
NODES: 2000000
TIME: 0
MATE: 0  # search for mate in X moves


# Search, PV and output behaviour
MAX_MOVES: 5  # number of moves to use from each PV iteration
               # Decreasing this number will provide more accurate analysis but will be slower.
MAX_ITER: 100  # maximum number of iterations to calculate
PRINT_BOARD: True  # whether to print the board after each iteration

STOP_ON_TBHIT: True  # whether to stop searching if a tablebase position
                     # (i.e. one with <= 7 pieces) is reached
QUERY_ON_TBHIT: True  # whether to query the online Lichess tablebase
                      # if a tablebase position is reached
STOP_ON_DRAW: 5  # stop searching if the last X consecutive iterations all returned 0.00 eval
                 # (useful to save computing time if the position is a dead draw)
                 # set to 0 to disable
STOP_ON_EVAL: 300  # stop searching if absolute value of the eval is >= X (in centipawns)
                   # set to 0 to disable

EXPORT_PGN: True  # whether to export the game to a PGN after the analysis is complete
                  # (the PGN will be saved in /pgns)
DETAILED_PGN: True  # whether to write detailed info (eval, depth, nodes) in the PGN
                    # only useful if EXPORT_PGN is True


ENGINE_OPTIONS:
  # Engine specific UCI options
  Threads: 1
  Hash: 64
