name: Build PVengine
run-name: Build PVengine executable
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build_linux:
    name: Build & test on Linux (Ubuntu)
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: src/engine
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install requirements
        run: pip3 install -r requirements.txt
      - run: pip3 install pyinstaller
      - run: pip3 install cx_Freeze
      - name: Build with pyinstaller
        run: sh build.sh
      - name: Test executable
        run: ./build/pvengine bench
      - name: Build with cx_Freeze
        run: sh build_fast.sh
      - name: Test executable
        run: ./build/pvengine bench

  build_macos:
    name: Build & test on MacOS
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
        working-directory: src/engine
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install requirements
        run: pip3 install -r requirements.txt
      - run: pip3 install pyinstaller
      - run: pip3 install cx_Freeze
      - name: Build with pyinstaller
        run: sh build.sh
      - name: Test executable
        run: ./build/pvengine bench
      - name: Build with cx_Freeze
        run: sh build_fast.sh
      - name: Test executable
        run: ./build/pvengine bench

  build_windows:
    name: Build & test on Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
        working-directory: src/engine
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install requirements
        run: pip install -r requirements.txt
      - run: pip install pyinstaller
      - run: pip install cx_Freeze
      - name: Build with pyinstaller
        run: python -m PyInstaller --onefile -n pvengine --distpath build main.py
      - name: Test executable
        run: build/pvengine.exe bench
      - name: Build with cx_Freeze
        run: python -m cx_Freeze -c main.py --target-dir=build --target-name=pvengine
      - name: Test executable
        run: build/pvengine.exe bench