# Acknowledgement to the Stockfish project for the workflow.

name: Delete old prelease
on:
  push:
    tags:
      - '*'
    branches:
      - main
      - ci_test

jobs:
  delete_old_prelease:
    name: Delete old prelease
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # returns null if no pre-release exists
      - name: Get Commit SHA of Latest Pre-release
        run: |
          # Install required packages
          sudo apt-get update
          sudo apt-get install -y curl jq

          echo "COMMIT_SHA=$(jq -r 'map(select(.prerelease)) | first | .tag_name' <<< $(curl -s https://api.github.com/repos/${{ github.repository_owner }}/PVplayer/releases))" >> $GITHUB_ENV

      # delete old previous pre-release and tag
      - uses: dev-drprasad/delete-tag-and-release@v0.2.1
        if: env.COMMIT_SHA != 'null'
        with:
          tag_name: ${{ env.COMMIT_SHA }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
