name: Run PVengine (startpos)
run-name: Run PVengine on startpos
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: cd src/engine
      - run: echo 'go' | python3 engine_main.py