name: Bench (startpos, depth 3)
run-name: Benchmark PVengine on startpos @ depth 3
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  bench_linux:
    name: Test on Linux (Ubuntu)
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: src/engine
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install requirements
        run: pip3 install -r requirements.txt
      - run: python3 main.py bench 3

  bench_macos:
    name: Test on MacOS
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
        working-directory: src/engine
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install requirements
        run: pip3 install -r requirements.txt
      - run: python3 main.py bench 3

  bench_windows:
    name: Test on Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
        working-directory: src/engine
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install requirements
        run: pip install -r requirements.txt
      - run: python main.py bench 3